### ISSUE TITLE
Simulate poorly preforming API

### ISSUE THREAD

**Issue by lfjewett** [csernazs/pytest-httpserver#31]
Testing failure mechanisms with external API's can be difficult when the pytest httpserver always responds back instantly.  It would be nice to have the option to pass ether a set delay or range to each path.  This would allow easier testing of fallback routines and backoff code.

Example
httpserver.expect_request("/poorly/performing/api", delay=1.8).respond_with_json(
        {"status": "3"}, status=503
    )

**Comment by csernazs** [comment]
Hi,

I think that this library's advantage is making the testing fast (compared to contacting with the busy production server), but I understand your idea.

Do you know that the library allows that you can specify a callable (eg. a function)?
That's `respond_with_handler`:
https://pytest-httpserver.readthedocs.io/en/latest/api.html#pytest_httpserver.RequestHandler.respond_with_handler


On the other hand, I think that your idea can be made a bit more generic.
Let's say passing a callable object (eg a function) which will be called right before sending the response so you could pass:

```python
httpserver.expect_request("/poorly/performing/api", side_effect=delay(1.5)).respond_with_json(
{"status": "3"}, status=503
)
```

So here, delay would be something like this (and it would be provided by the library):
```python

def delay(secs):
    def delay_func():
        time.sleep(secs)
    return delay_func
```

So with this API, it could be flexible, you could write your own function (let's say if you want to add more randomness or whatever) which will be called before the response is sent.

This would also allow to have some side effects caused by serving the request, eg do logging, etc.

What do you think about these?

**Comment by lfjewett** [comment]
I didn't see the `respond_with_handler` on my first pass through the docs no.  The second option you posted above is pretty much exactly what I was looking for.  I will see if I can work out how to use the  respond_with_handler and respond back if I can get something useful for others that might stumble upon this.
