### ISSUE TITLE
turn off (disable) fixture httpserver for some tests

### ISSUE THREAD

**Issue by ViktorL-github** [csernazs/pytest-httpserver#54]
Hello csernazs.

There are several test cases, where I should be emulate timeout (connection error) to httpserver.

If I run one (current) test file by name without fixture httpserver inside - then my app have connection error and test case passed.
But if I run pytest for several test files (fixture httpserver used inside other test files in folder) - then pytest used fixture httpserver global, and httserver return 500 status instead connection error (timeout) for my app.

Can you provide example, how I can to turn off (disable) fixture httpserver for some tests in folder?

Best Regards,
Viktor L.

**Comment by csernazs** [comment]
Hi,

Use the stop method of the httpserver fixture. This will will stop the server thread and there will be no server listening. This means that the next request will receive "Connection reset by peer" error (on Linux). Stopping and starting (it will be started on the next test running when it is using the fixture) have some time penalty so that's why it is not done by the library between the tests.

Example:
```python

def test_bar(httpserver: HTTPServer):
    httpserver.stop()
    httpserver.expect_request("/foo").respond_with_data("foo") # this is optional, it shows that even adding a new request handler won't start the server
    assert requests.get(httpserver.url_for("/foo")).text == "foo"

```

If you need to have connection timeout instead connection reset by peer, then you still need a running server which just accepts the request and then waits for a given time period, so the client will timeout.

Although this has some unwanted side effects (timing should be adjusted precisely, test running will waste time), this example works for me:

```python

import time
import re
from pytest_httpserver import HTTPServer
import requests

def sleeping(request):
    time.sleep(2) # this should be greater than the client's timeout parameter


def test_timeout(httpserver: HTTPServer):
    httpserver.expect_request(re.compile(".*")).respond_with_handler(sleeping)
    assert requests.get(httpserver.url_for("/baz"), timeout=1).text == "baz"
```


But besides the above, I think I don't really understand every detail of your issue. When the httpserver is started, it starts to listen on a random TCP port, so in order to connect to it, you need to use that port, that's why the url_for() method is implemented. If you are not using the fixture, how that test can connect to the server? My guess is that this could be either by storing the url in some kind of a global variable, or running the server on a fixed port.

**Comment by ViktorL-github** [comment]
Hello csernazs!

Thank you very much for your examples. This is what I need.
If documentation will be contain this examples, maybe, that can help another developers.

Best Regards,
Viktor L.

**Comment by csernazs** [comment]
Thanks!
I've updated the documentation at https://pytest-httpserver.readthedocs.io/en/latest/howto.html
