### ISSUE TITLE
MyPy complains when trying to update DEFAULT_MATCHERS

### ISSUE THREAD

**Issue by MaxShvets** [csernazs/pytest-httpserver#93]
The advanced header matching section of the documentation suggests that to set a custom header matcher globally one can do: 
```python
HeaderValueMatcher.DEFAULT_MATCHERS["X-Foo"] = some_matcher
```
However, when attempting to actually do that in a project that uses mypy one gets the following error:
```
Unsupported target for indexed assignment ("Mapping[str, Callable[[Optional[str], str], bool]]")
```

**Comment by csernazs** [comment]
Thanks for the PR! 

Could you please try it with `MutableMapping`? I think that the issue was that `Mapping` doesn't have `__setitem__`.
Theoretically speaking, I thing `MutableMapping` would cover it better but YMMV. If you don't think so (or you don't want to put the extra effort) then I'm happy to approve this in its current form, just let me know.

**Comment by csernazs** [comment]
PR #94 merged, thank you. I can do the release tomorrow if that works for you (unfortunately that's still manual).

**Comment by MaxShvets** [comment]
Yeah, no hurry, thanks!

**Comment by csernazs** [comment]
Version 1.0.4 has been released with your fixes. Thanks! :)

**Comment by MaxShvets** [comment]
Thanks!
